//
//  TRPCClient.swift
//  Generated by trpc-swift
//  Library Author: Marko Calasan
//

import Foundation

public enum DecodableValue: Decodable {
    case string(String)
    case int(Int)
    case double(Double)
    case bool(Bool)
    case dictionary([String: DecodableValue])
    case array([DecodableValue])
    
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let str = try? container.decode(String.self) {
            self = .string(str)
        } else if let int = try? container.decode(Int.self) {
            self = .int(int)
        } else if let dbl = try? container.decode(Double.self) {
            self = .double(dbl)
        } else if let bool = try? container.decode(Bool.self) {
            self = .bool(bool)
        } else if let array = try? container.decode([DecodableValue].self) {
            self = .array(array)
        } else {
            let dict = try container.decode([String: DecodableValue].self)
            self = .dictionary(dict)
        }
    }
}

public enum TRPCErrorCode: Int, Codable {
    // tRPC Defined
    case parseError = -32700
    case badRequest = -32600
    case internalServerError = -32603
    case unauthorized = -32001
    case forbidden = -32003
    case notFound = -32004
    case methodNotSupported = -32005    
    case timeout = -32008
    case conflict = -32009
    case preconditionFailed = -32012
    case payloadTooLarge = -32013
    case unprocessableContent = -32022
    case tooManyRequests = -32029
    case clientClosedRequest = -32099
    
    // Application Defined
    case unknown = -1
    case missingOutputPayload = -2
    case errorParsingUrl = -3
    case errorParsingUrlComponents = -4
}

public struct TRPCError: Error, Decodable {
    public let code: TRPCErrorCode
    public let message: String?
    public let data: DecodableValue?
    
    init(code: TRPCErrorCode, message: String? = nil, data: DecodableValue? = nil) {
        self.code = code
        self.message = message
        self.data = data
    }
}

struct TRPCResponse<T: Decodable>: Decodable {
    struct Result: Decodable {
        let data: T?
    }
    
    let result: Result?
    let error: TRPCError?
}

public struct TRPCSwiftFile: Equatable, Hashable {
    let filename: String
    let content: Data

    public init(filename: String, content: Data) {
        self.filename = filename
        self.content = content
    }
    
    public init(fileExtension: String, content: Data) {
        let processedExtension = fileExtension.hasPrefix(".") ? fileExtension : ".\(fileExtension)"
        self.filename = "\(UUID().uuidString)\(processedExtension)"
        self.content = content
    }
}

protocol TRPCSwiftMultipartParsable {
    var jsonFields: [String: Encodable?] { get }
    var fileFields: [String: TRPCSwiftFile?] { get }
}

public typealias TRPCMiddleware = (URLRequest) async throws -> URLRequest

class TRPCClient {
    class SSEClient<TOutput: Decodable>: NSObject, URLSessionDataDelegate {
        private var task: URLSessionDataTask?
        
        let onMessage: (TOutput) throws -> Void
        let onClose: (Error?) -> Void

        var didCrash = false
        
        init(request: URLRequest, onMessage: @escaping (TOutput) throws -> Void, onClose: @escaping (Error?) -> Void) {
            self.onMessage = onMessage
            self.onClose = onClose

            super.init()
            let config = URLSessionConfiguration.default
            let session = URLSession(configuration: config, delegate: self, delegateQueue: OperationQueue())
            self.task = session.dataTask(with: request)
        }
        
        func start() {
            task?.resume()
        }
        
        func stop() {
            task?.cancel()
        }
        
        func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive data: Data) {
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .formatted(dateFormatter)

            guard let eventString = String(data: data, encoding: .utf8) else {
                return
            }
            
            let eventLines = eventString.components(separatedBy: "\n")
            let dataPrefix = "data: "
            let isErrorEvent = eventLines.contains("event: serialized-error")

            for line in eventLines {
                if line.hasPrefix(dataPrefix) {
                    let dataJsonString = String(line[line.index(line.startIndex, offsetBy: dataPrefix.count)...])
                    do {
                        if isErrorEvent {
                            let error = try decoder.decode(TRPCError.self, from: dataJsonString.data(using: .utf8)!)
                            throw error
                        } else {
                            let response = try decoder.decode(TOutput.self, from: dataJsonString.data(using: .utf8)!)
                            try self.onMessage(response)
                        }
                    } catch {
                        self.didCrash = true
                        self.onClose(error)
                        self.task?.cancel()
                    }

                    break
                }
            }
        }

        func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?) {
            guard !didCrash else {
                return
            }
            
            if let error = error, (error as NSError).code != NSURLErrorCancelled {
                self.onClose(error)
            } else {
                self.onClose(nil)
            }
        }
    }

    struct EmptyObject: Codable { }
    
    static var dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        
        return formatter
    }()
    
    static func sendQuery<Request: Encodable, Response: Decodable>(url: URL, middlewares: [TRPCMiddleware], input: Request) async throws -> Response {
        let urlWithParams = try createURLWithParameters(url: url, input: input)
        return try await send(url: urlWithParams, httpMethod: "GET", middlewares: middlewares, contentType: "application/json", bodyData: nil)
    }
    
    static func sendMutation<Request: Encodable, Response: Decodable>(url: URL, middlewares: [TRPCMiddleware], input: Request) async throws -> Response {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .formatted(dateFormatter)
        let data = try encoder.encode(Request.self == EmptyObject.self ? nil : input)
        
        return try await send(url: url, httpMethod: "POST", middlewares: middlewares, contentType: "application/json", bodyData: data)
    }

    static func sendMultipartMutation<Request: TRPCSwiftMultipartParsable, Response: Decodable>(url: URL, middlewares: [TRPCMiddleware], input: Request) async throws -> Response {
        let boundary = "TRPCSwiftMultipart-\(UUID().uuidString)"
        let data = try createMultipartData(input: input, boundary: boundary)
        return try await send(url: url, httpMethod: "POST", middlewares: middlewares, contentType: "multipart/form-data; boundary=\(boundary)", bodyData: data)
    }
    
    static func startSubscription<Request: Encodable, Response: Decodable>(url: URL, middlewares: [TRPCMiddleware], input: Request, onMessage: @escaping (Response) throws -> Void) async throws {
        let urlWithParams = try createURLWithParameters(url: url, input: input)

        var request = URLRequest(url: urlWithParams)
        for middleware in middlewares {
            request = try await middleware(request)
        }

        try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
            let client = SSEClient(request: request) { response in
                try onMessage(response)
            } onClose: { error in
                if let error = error {
                    continuation.resume(throwing: error)
                } else {
                    continuation.resume()
                }
            }
            client.start()
        }
    }

    static func createMultipartData(input: TRPCSwiftMultipartParsable, boundary: String) throws -> Data {
        var body = Data()
        
        for (key, value) in input.jsonFields {
            guard let value = value else {
                continue
            }

            body.append("--\(boundary)\r\n".data(using: .utf8)!)
            body.append("Content-Disposition: form-data; name=\"\(key)\"\r\n".data(using: .utf8)!)
            body.append("Content-Type: application/json\r\n\r\n".data(using: .utf8)!)
            body.append(try JSONEncoder().encode(value))
            body.append("\r\n".data(using: .utf8)!)
        }
        
        for (key, file) in input.fileFields {
            guard let file = file else {
                continue
            }
            
            body.append("--\(boundary)\r\n".data(using: .utf8)!)
            body.append("Content-Disposition: form-data; name=\"\(key)\"; filename=\"\(file.filename)\"\r\n".data(using: .utf8)!)
            body.append("Content-Type: application/octet-stream\r\n\r\n".data(using: .utf8)!)
            body.append(file.content)
            body.append("\r\n".data(using: .utf8)!)
        }
        
        body.append("--\(boundary)--\r\n".data(using: .utf8)!)
        
        print(String(data: body, encoding: .utf8)!)
        return body
    }
    
    private static func send<Response: Decodable>(url: URL, httpMethod: String, middlewares: [TRPCMiddleware], contentType: String, bodyData: Data?) async throws -> Response {
        var request = URLRequest(url: url)
        request.httpMethod = httpMethod
        request.httpBody = bodyData
        request.addValue(contentType, forHTTPHeaderField: "Content-Type")
        
        for middleware in middlewares {
            request = try await middleware(request)
        }
        
        request.httpMethod = httpMethod
        request.httpBody = bodyData
        
        let response = try await URLSession.shared.data(for: request)
        
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .formatted(dateFormatter)
        let decoded = try decoder.decode(TRPCResponse<Response>.self, from: response.0)
        
        if let error = decoded.error {
            throw error
        }
        
        if let data = decoded.result?.data {
            return data
        }
        
        if Response.self == EmptyObject.self {
            guard let emptyResult = EmptyObject() as? Response else {
                throw TRPCError(code: .missingOutputPayload, message: "Cannot cast empty object to \(Response.self).", data: nil)
            }
            
            return emptyResult
        }
        
        throw TRPCError(code: .missingOutputPayload, message: "Missing output payload.", data: nil)
    }
    
    private static func createURLWithParameters<Request: Encodable>(url: URL, input: Request) throws -> URL {
        guard var components = URLComponents(url: url, resolvingAgainstBaseURL: false) else {
            throw TRPCError(code: .errorParsingUrl, message: "Could not create URLComponents from the given url: \(url)")
        }
        
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .formatted(dateFormatter)
        let data = try encoder.encode(Request.self == EmptyObject.self ? nil : input)
        
        components.queryItems = [
        URLQueryItem(name: "input", value: String(data: data, encoding: .utf8)!)
        ]
        
        let characterSet = CharacterSet(charactersIn: "/+").inverted
        guard let oldPercentEncodedQuery = components.percentEncodedQuery else {
            throw TRPCError(code: .errorParsingUrlComponents, message: "Could not retreive percent encoded URL query.")
        }
        components.percentEncodedQuery = oldPercentEncodedQuery.addingPercentEncoding(withAllowedCharacters: characterSet)
        
        guard let url = components.url else {
            throw TRPCError(code: .errorParsingUrlComponents, message: "Could not generate final URL after including parameters.")
        }
        
        return url
    }
}
